import {useEffect,useState} from 'react';
import {ArrowUpRight,Send,Database,Info} from 'lucide-react';
import type {Context,Module,Selection,Variable,ForecastValue,StateOutlook} from './types';
import {fmt,get,label,post} from './api';
import {ChartCard,Donut,HBars,GroupedBars,PALETTE} from './Charts';
import RollingRainfall from './RollingRainfall';

export function Empty({children}:{children:React.ReactNode}){return <div className="empty"><Info size={22}/><h3>Loading location intelligence</h3><p>{children}</p></div>;}
export function Weights({value}:{value:ForecastValue|undefined}){return value?.experts.length?<div className="weights">{value.experts.map((e,i)=><div key={e.name}><div className="weight-label"><span><i style={{background:['#d6a85f','#76a394','#8f9fba','#b199b9'][i%4]}}/>{label(e.name)}</span><strong>{fmt(e.weight*100,1)}%</strong></div><div className="track"><i style={{width:`${e.weight*100}%`,background:['#d6a85f','#76a394','#8f9fba','#b199b9'][i%4]}}/></div></div>)}</div>:<p className="muted">No learned expert weights for this source.</p>;}
export function Metrics({ctx}:{ctx:Context|null}){
 const observation=ctx?.observations;
 return <><div className="metrics">{(['tp_mm','t2m_C_mean','wind_speed_mean'] as Variable[]).map((k,i)=>{const v=ctx?.forecast[k];return <div className="metric" key={k}><small>{['DAILY RAINFALL','MEAN TEMPERATURE','MEAN WIND'][i]}</small><strong>{fmt(v?.value)} <em>{v?.unit||['mm/day','°C','m/s'][i]}</em></strong><span>{v?.minimum!=null&&v?.maximum!=null?`State range ${fmt(v.minimum)} – ${fmt(v.maximum)}`:v?.interval80?`80% interval ${fmt(v.interval80[0])} – ${fmt(v.interval80[1])}`:'Interval unavailable'}</span></div>})}</div>{ctx?.scope==='state'&&observation?.status==='available'&&<div className="state-observation"><div><small>IMD STATE OBSERVATION · {String(observation.date)}</small><strong>{fmt(Number(observation.daily_actual_mm))} mm</strong></div><div><span>Daily category</span><b>{label(String(observation.daily_category))}</b></div><div><span>Departure from normal</span><b>{fmt(Number(observation.daily_departure_pct),0)}%</b></div></div>}</>;
}

function Verification({variable,lead}:{variable:Variable;lead:number}){
 const [season,setSeason]=useState('post_monsoon'),[data,setData]=useState<{rows:Record<string,string>[];scope:string}|null>(null),[error,setError]=useState('');
 useEffect(()=>{const ac=new AbortController();setData(null);setError('');get<{rows:Record<string,string>[];scope:string}>(`verification?variable=${variable}&lead=${lead||24}&season=${season}`,ac.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>ac.abort();},[variable,lead,season]);
 return <><div className="sectionline"><h3>Held-out forecast skill</h3><select aria-label="Verification season" value={season} onChange={e=>setSeason(e.target.value)}>{['winter','pre_monsoon','monsoon','post_monsoon'].map(s=><option key={s}>{s}</option>)}</select></div><p className="note">2025 · {lead||24}h · {label(variable)} · ERA5 reference</p><p className="muted">{data?.scope}</p>{error?<p role="alert">{error}</p>:!data?<p>Loading benchmark…</p>:<><ChartCard title="Error by model (lower is better)" subtitle={`RMSE vs MAE · ${label(variable)} · ${season.replace('_',' ')}`}><GroupedBars groups={data.rows.map(r=>({name:label(r.model),values:[{label:'RMSE',value:+r.rmse},{label:'MAE',value:+r.mae}]}))} seriesColors={{RMSE:'#d6a85f',MAE:'#76a394'}}/></ChartCard><table><thead><tr><th>Model</th><th>RMSE</th><th>MAE</th><th>Samples</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.model} className={r.model==='gating_adaptive'?'highlight':''}><td>{label(r.model)}</td><td>{fmt(+r.rmse)}</td><td>{fmt(+r.mae)}</td><td>{fmt(+r.n,0)}</td></tr>)}</tbody></table></>}<p className="footnote">Errors use the selected variable's units. Benchmark results are imported from the repository; no observation matching for the current location is implied.</p></>;
}

type CurrentObservation={status:string;message:string;source:string;updated_at?:string;cached?:boolean;cache_minutes?:number;observation?:{city:string;state:string;temperature_max_C:number|null;temperature_min_C:number|null;rainfall_mm:number|null;humidity_percent:number|null;description:string|null;forecast_date:string|null;wind_speed_kmh?:number|null;cloud_cover_percent?:number|null;pressure_hpa?:number|null;provider?:string}};
function Observations({selection}:{selection:Selection}){
 const [data,setData]=useState<CurrentObservation|null>(null),[error,setError]=useState('');
 useEffect(()=>{const ac=new AbortController(),state=selection.state?`&state=${encodeURIComponent(selection.state)}`:'';setData(null);setError('');get<CurrentObservation>(`current-observation?latitude=${selection.latitude}&longitude=${selection.longitude}${state}`,ac.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>ac.abort();},[selection.latitude,selection.longitude,selection.state]);
 const observation=data?.observation;
 return <><h3>Current weather</h3><p className="muted">{data?.source||'Loading provider…'} · refreshed server-side</p>{error?<p role="alert">{error}</p>:!data?<p>Loading current weather…</p>:data.status==='available'&&observation?<><div className="hero-number">{fmt(observation.temperature_max_C)} <small>°C</small></div><p>{observation.city}, {observation.state}</p><div className="datarow"><span>Precipitation</span><b>{fmt(observation.rainfall_mm)} mm</b></div><div className="datarow"><span>Humidity</span><b>{fmt(observation.humidity_percent,0)}%</b></div><div className="datarow"><span>Wind</span><b>{fmt(observation.wind_speed_kmh)} km/h</b></div><div className="datarow"><span>Cloud cover</span><b>{fmt(observation.cloud_cover_percent,0)}%</b></div><div className="datarow"><span>Surface pressure</span><b>{fmt(observation.pressure_hpa,0)} hPa</b></div><div className="datarow"><span>Outlook</span><b>{observation.description||'—'}</b></div><p className="note">{data.message} Updated {data.updated_at?new Date(data.updated_at).toLocaleString():'—'}{data.cached?` · cached up to ${data.cache_minutes} minutes`:''}.</p></>:<Empty>{data.message}</Empty>}</>;
}

function ScenarioLab({selection,ctx}:{selection:Selection;ctx:Context|null}){
 const [rain,setRain]=useState(20),[wind,setWind]=useState(0),[temp,setTemp]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{label:string;values:Record<string,{baseline:number;simulated:number;unit:string}>;risk:{message:string}}|null>(null);
 useEffect(()=>{setResult(null);setError('')},[selection.latitude,selection.longitude,selection.lead,selection.source]);
 const run=async()=>{setBusy(true);setError('');try{setResult(await post('scenario',{...selection,rain_percent:rain,wind_percent:wind,temperature_delta:temp}))}catch(e){setError(String(e))}finally{setBusy(false)}};
 return <><p className="note">SIMULATION · Perturb the selected weather values. Probabilities and impact are not inferred from these changes.</p>{[['Rainfall change',rain,setRain,-100,100,'%'],['Wind change',wind,setWind,-100,100,'%'],['Temperature change',temp,setTemp,-10,10,'°C']].map(([name,value,setter,min,max,unit])=><label className="slider" key={String(name)}><span>{String(name)}<b>{Number(value)>0?'+':''}{String(value)}{String(unit)}</b></span><input aria-label={String(name)} type="range" min={Number(min)} max={Number(max)} value={Number(value)} onChange={e=>{(setter as (v:number)=>void)(+e.target.value);setResult(null)}}/></label>)}<button className="primary" disabled={busy||ctx?.status!=='available'} onClick={run}>{busy?'Calculating…':'Run scenario'} <ArrowUpRight size={14}/></button>{ctx?.status!=='available'&&<p>Select a location with supplied forecast data first.</p>}{error&&<p role="alert">{error}</p>}{result&&<><h3>{result.label}</h3><table><thead><tr><th>Variable</th><th>Baseline</th><th>Scenario</th></tr></thead><tbody>{Object.entries(result.values).map(([k,v])=><tr key={k}><td>{label(k)}</td><td>{fmt(v.baseline)} {v.unit}</td><td>{fmt(v.simulated)} {v.unit}</td></tr>)}</tbody></table><p className="note">{result.risk.message}</p></>}</>;
}

type ParsedIntent={location?:string|null;location_suggestion?:string|null;resolved_location?:{name?:string}|null;weather_variable?:string|null;data_layer?:string|null;query_bucket?:string|null;question_operation?:string|null;ranking_direction?:string|null;ranking_scope?:string|null;explanation_topic?:string|null;use_case?:string;extreme_event_type?:string|null;grid_cell?:string|null;model_evidence_request?:boolean;time_range?:{text?:string|null;start_date?:string|null;end_date?:string|null}};
function intentText(parsed:ParsedIntent|undefined){if(!parsed)return undefined;const location=parsed.resolved_location?.name||parsed.location||parsed.location_suggestion;const time=parsed.time_range?.start_date&&parsed.time_range?.end_date&&parsed.time_range.start_date!==parsed.time_range.end_date?`${parsed.time_range.start_date} to ${parsed.time_range.end_date}`:parsed.time_range?.text;const parts=[location&&`Location: ${location}${parsed.location_suggestion?' (suggested)':''}`,parsed.grid_cell&&`Grid cell: ${parsed.grid_cell}`,parsed.weather_variable&&`Variable: ${parsed.weather_variable}`,parsed.query_bucket&&`Bucket: ${parsed.query_bucket.replaceAll('_',' ')}`,parsed.question_operation&&`Operation: ${parsed.question_operation.replaceAll('_',' ')}`,parsed.ranking_scope==='states'&&'Scope: state/UT representative readings',parsed.explanation_topic&&parsed.explanation_topic!=='forecast_value'&&`Logic: ${parsed.explanation_topic.replaceAll('_',' ')}`,parsed.model_evidence_request&&'Evidence: saved HYDRA allocations',parsed.ranking_direction==='ascending'&&'Ranking: lowest first',parsed.data_layer&&`Layer: ${parsed.data_layer.replaceAll('_',' ')}`,parsed.use_case&&parsed.use_case!=='general'&&`Use case: ${parsed.use_case}`,time&&`Time: ${time}`,parsed.extreme_event_type&&`Event: ${parsed.extreme_event_type.replace('_',' ')}`].filter(Boolean);return parts.length?parts.join(' · '):undefined;}
function FormattedAnswer({text}:{text:string}){const lines=text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);return <div className="chat-answer-body">{lines.map((line,index)=>{const rank=line.match(/^(\d+)\.\s+(.+)$/);if(rank)return <div className="answer-rank" key={`${index}-${line}`}><b>{rank[1]}</b><span>{rank[2]}</span></div>;const section=line.match(/^([A-Za-z][A-Za-z /-]{1,45}):\s*(.+)$/);if(section)return <div className="answer-section" key={`${index}-${line}`}><strong>{section[1]}</strong><span>{section[2]}</span></div>;return <p className={index===0?'answer-lead':''} key={`${index}-${line}`}>{line}</p>;})}</div>}
const SESSION_ID=`wgpt-${Math.random().toString(36).slice(2)}-${Date.now().toString(36)}`;
function Chat({selection}:{selection:Selection}){
 const [question,setQuestion]=useState(''),[items,setItems]=useState<{q:string;a:string;file?:string;intent?:string;followups?:string[]}[]>([]),[busy,setBusy]=useState(false);
 useEffect(()=>setItems([]),[selection.latitude,selection.longitude,selection.lead,selection.source]);
 async function ask(q:string){if(!q.trim()||busy)return;setBusy(true);setQuestion('');try{const r=await post<{answer:string;evidence:Record<string,unknown>[];parsed_query?:ParsedIntent;followups?:string[]}>( 'weathergpt',{...selection,question:q,session_id:SESSION_ID});setItems(v=>[...v,{q,a:r.answer,file:r.evidence?.[0]?.file as string,intent:intentText(r.parsed_query),followups:r.followups}])}catch(e){setItems(v=>[...v,{q,a:String(e)}])}finally{setBusy(false)}}
 const last=items[items.length-1];
 return <><p className="note">Grounded weather and model explainer · live, forecast and past data for every state · follow-up questions keep context</p><div className="suggestions">{(last?.followups?.length?last.followups:['Which state got the most rain last week?','Will it rain in Mumbai tomorrow?','Was Bihar above normal this season?','How accurate is HYDRA in Kerala?','kal Delhi mein barish hogi kya']).map(q=><button disabled={busy} key={q} onClick={()=>ask(q)}>{q}</button>)}</div><div className="chatlog" aria-live="polite">{!items.length&&<div className="chat-answer"><FormattedAnswer text="Ask anything about Indian weather (live, forecast or past, any state or city) or about HYDRA's forecasts, accuracy and experts. Each answer states its source and coverage."/></div>}{items.map((m,i)=><div key={i}><div className="chat-question">{m.q}</div><div className="chat-answer"><FormattedAnswer text={m.a}/>{m.intent&&<small>Parsed intent · {m.intent}</small>}{m.file&&<small><Database size={12}/> {m.file}</small>}</div></div>)}{busy&&<p>Reading forecast evidence…</p>}</div><form className="chatform" onSubmit={e=>{e.preventDefault();ask(question)}}><input aria-label="WeatherGPT question" placeholder="Ask about any state, date, forecast, or HYDRA's accuracy…" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)}/><button aria-label="Send question" disabled={busy||!question.trim()}><Send size={16}/></button></form></>;
}

function StateForecastBriefing({outlook}:{outlook:StateOutlook|null}){
 const hydra=outlook?.hydra,provider=outlook?.provider_comparison;
 if(hydra?.status!=='available')return <Empty>{hydra?.message||'Select a state with an available HYDRA forecast to open its briefing.'}</Empty>;
 const targets=['tp_mm','t2m_C_mean','wind_speed_mean'] as Variable[];
 return <div className="state-briefing">
  <section className="state-briefing-hero"><small>STATE-AWARE WEATHERGPT BRIEFING</small><h3>{hydra.state} · HYDRA neural-gating forecast</h3><p>Issued {hydra.issue_date||'from the published model cycle'} · {hydra.outlooks.length} forecast windows · {hydra.outlooks[0]?.grid_cell_count||'—'} state grid cells.</p></section>
  <section className="briefing-method"><strong>How this forecast is produced</strong><p>HYDRA’s neural gate assigns a learned allocation across climatology, persistence, recent-three-day, and anomaly-persistence experts for each variable and lead. The displayed forecast is their weighted blend. Expert weights describe the model allocation; they are not causal feature importance.</p></section>
  {hydra.outlooks.map(window=><section className="briefing-window" key={window.lead_hours}>
   <header><div><small>HYDRA FORECAST WINDOW</small><h3>+{window.lead_hours} hours</h3></div><span>{window.valid_date||'Valid date unavailable'}</span></header>
   <div className="briefing-metric-grid">{targets.map(target=>{const metric=window.forecast[target];if(!metric)return null;const dominant=[...metric.experts].sort((a,b)=>b.weight-a.weight)[0];return <article className="briefing-metric" key={target}>
    <div className="briefing-metric-head"><span>{label(target)}</span><small>{metric.unit}</small></div><strong>{fmt(metric.value)} <em>{metric.unit}</em></strong>
    <div className="briefing-range"><span>80% range</span><b>{metric.interval80?`${fmt(metric.interval80[0])}–${fmt(metric.interval80[1])} ${metric.unit}`:'Not supplied'}</b></div>{metric.interval_note&&<p className="briefing-explanation warn">{metric.interval_note}</p>}
    <div className="briefing-model-callout"><span>Largest allocation</span><b>{dominant?`${label(dominant.name)} · ${fmt(dominant.weight*100,1)}%`:'Unavailable'}</b></div>
    <HBars unit={metric.unit} bars={metric.experts.map(e=>({label:label(e.name),value:e.value}))} reference={metric.value} referenceLabel="HYDRA" band={metric.interval80}/><div className="briefing-weights">{metric.experts.map(expert=><div key={expert.name}><span>{label(expert.name)}</span><i><b style={{width:`${expert.weight*100}%`}}/></i><strong>{fmt(expert.weight*100,1)}%</strong></div>)}</div>
    <div className="briefing-validation"><span>Expert spread <b>{fmt(metric.spread)} {metric.unit}</b></span>{metric.backtest_error&&<><span>Held-out MAE <b>{fmt(metric.backtest_error.mae)} {metric.unit}</b></span><span>RMSE <b>{fmt(metric.backtest_error.rmse)} {metric.unit}</b></span><small>{metric.backtest_error.samples} chronological backtest samples</small></>}</div>
   </article>})}</div>
   <p className="briefing-explanation">Disagreement is the spread across HYDRA’s expert forecasts. The 80% range is a split-conformal central band (α = 0.20) from held-out chronological backtest residuals for this state, target, and lead; it is an error band, not a probability that any individual expert is correct.</p>
  </section>)}
  <section className="briefing-provider"><div className="sectionline"><h3>Live provider comparison</h3><span className="badge">REFERENCE ONLY</span></div><p>Open-Meteo is displayed beside HYDRA for operational comparison. It does not provide HYDRA’s forecast, weights, uncertainty band, or backtest scores.</p>{provider?.status==='available'&&<><ChartCard title="HYDRA vs Open-Meteo · temperature" subtitle="Daily mean, °C"><GroupedBars unit="°C" seriesColors={{HYDRA:'#d6a85f','Open-Meteo':'#8f9fba'}} groups={hydra.outlooks.map(w=>({name:`+${w.lead_hours}h`,values:[{label:'HYDRA',value:w.forecast.t2m_C_mean?.value},{label:'Open-Meteo',value:provider.outlooks?.find(o=>o.lead_hours===w.lead_hours)?.temperature_mean_C}]}))}/></ChartCard><ChartCard title="HYDRA vs Open-Meteo · rainfall" subtitle="Daily total, mm"><GroupedBars unit="mm" seriesColors={{HYDRA:'#d6a85f','Open-Meteo':'#8f9fba'}} groups={hydra.outlooks.map(w=>({name:`+${w.lead_hours}h`,values:[{label:'HYDRA',value:w.forecast.tp_mm?.value},{label:'Open-Meteo',value:provider.outlooks?.find(o=>o.lead_hours===w.lead_hours)?.rainfall_total_mm}]}))}/></ChartCard></>}{provider?.status==='available'?<div className="briefing-provider-grid">{provider.outlooks?.map(window=><div key={window.lead_hours}><b>+{window.lead_hours}h</b><span>Temperature {fmt(window.temperature_mean_C)} °C</span><span>Rainfall {fmt(window.rainfall_total_mm)} mm</span><span>Humidity {fmt(window.humidity_mean_percent)}%</span></div>)}</div>:<p className="muted">{provider?.message||'No live provider comparison is available.'}</p>}</section>
  <section className="briefing-interpretation"><strong>How to read this briefing</strong><p>Use the HYDRA values for the model forecast. Compare the expert allocations to see which historical signal the gate relied on most. Use expert spread to assess model disagreement and the held-out MAE/RMSE to understand the model’s historical error for this state and lead.</p></section>
 </div>;
}
function Operations(){const [data,setData]=useState<{status:string;missing:string[];stages:{name:string;status:string}[];sources:{name:string;status:string}[]}|null>(null),[error,setError]=useState('');useEffect(()=>{get<typeof data>('health').then(setData).catch(e=>setError(e.message))},[]);return error?<p>{error}</p>:!data?<p>Checking services…</p>:<><div className="sectionline"><h3>Pipeline status</h3><span className="badge">{data.status}</span></div><div className="opsgrid">{data.stages.map(s=><div className="card" key={s.name}><small>{s.name}</small><strong className={s.status==='available'?'green':'amber'}>{s.status}</strong></div>)}</div><h3>Source registry</h3>{data.sources.map(s=><div className="datarow" key={s.name}><span>{s.name}</span><span>{s.status}</span></div>)}<p className="note">No live ingestion cycle has run. Checkpoint availability does not mean inference is ready. Missing: {data.missing.join(', ')||'none'}.</p><a href="/api/docs" target="_blank" rel="noreferrer">Open API documentation ↗</a></>;}

export default function Analytics({module,ctx,selection,variable,open,stateOutlook,states=[]}:{module:Module;ctx:Context|null;selection:Selection;variable:Variable;open:(m:Module)=>void;stateOutlook?:StateOutlook|null;states?:{name:string;code:string}[]}){
 const value=ctx?.forecast[variable];
 if(module==='Situation')return <RollingRainfall selectedState={selection.state} states={states}/>;
 if(module==='Operations')return <Operations/>;
 if(module==='Verification')return <Verification variable={variable} lead={selection.lead}/>;
 if(module==='Observations')return <Observations selection={selection}/>;
 if(module==='WeatherGPT')return <Chat selection={selection}/>;
 if(module==='State Forecast Briefing')return <StateForecastBriefing outlook={stateOutlook||null}/>;
 if(module==='Scenario')return <ScenarioLab selection={selection} ctx={ctx}/>;
 if(module==='Provenance')return <><h3>Source record</h3><pre>{JSON.stringify(ctx?.provenance||{message:'No forecast at this location'},null,2)}</pre></>;
 if(module==='Impact & Risk'||module==='Sectors')return <><Metrics ctx={ctx}/><Empty>{module==='Sectors'?'Agriculture, energy, aviation, marine, urban and infrastructure impact require sector models and exposure data. The supplied repository contains weather models only.':ctx?.risk.message}</Empty><button onClick={()=>open('Scenario')}>Explore a weather scenario <ArrowUpRight size={14}/></button></>;
 if(!ctx||ctx.status!=='available')return <Empty>{ctx?.message||'Select a location to load its forecast.'}</Empty>;
 if(module==='Extreme Events')return <><p className="note">{ctx.valid_date} · Daily threshold probabilities. These are model predictions, not confirmed events or official warnings.</p>{ctx.events.length?ctx.events.map(e=><div className="event-card" key={e.id}><div><small>CALIBRATED CLASSIFIER</small><h3>{e.name}</h3><p>{e.threshold}</p></div><strong>{e.probability==null?'Unavailable':`${fmt(e.probability*100,1)}%`}</strong><div className="event-actions"><button onClick={()=>open('Models')}>Compare models</button><button onClick={()=>open('Impact & Risk')}>View risk</button></div></div>):<Empty>No calibrated event probabilities in this source.</Empty>}<p className="footnote">Subdaily peak time, affected polygon, severity, and exposure are unavailable. The heatwave label is the repository's threshold definition.</p></>;
 return <><p className="note">{ctx.source==='ecmwf'?'ECMWF analysis':'HYDRA adaptive blend'} · issued {ctx.issue_date} · valid {ctx.valid_date}</p><Metrics ctx={ctx}/>{value?.experts.length?<div className="analytics-grid"><ChartCard title="Expert allocation" subtitle="Share of the neural-gate blend"><Donut items={value.experts.map((e,i)=>({label:label(e.name),value:e.weight,color:PALETTE[i%PALETTE.length]}))}/></ChartCard><ChartCard title="Expert forecasts vs blend" subtitle={`Dashed line = HYDRA blend · shaded = 80% interval · ${value.unit}`}><HBars unit={value.unit} bars={value.experts.map(e=>({label:label(e.name),value:e.value}))} reference={value.value} referenceLabel="HYDRA" band={value.interval80}/></ChartCard></div>:null}<div className="analytics-grid"><section className="card"><h3>Neural expert allocation</h3><Weights value={value}/><p className="footnote">Weights belong to the selected variable, location and lead.</p></section><section className="card"><h3>Forecast interpretation</h3><div className="datarow"><span>Weather regime</span><b>{ctx.regime?label(ctx.regime):'Unavailable'}</b></div><div className="datarow"><span>Expert disagreement</span><b>{fmt(value?.spread)} {value?.unit}</b></div><div className="datarow"><span>Calibrated confidence</span><b>Unavailable</b></div><p className="muted">Disagreement is the standard deviation across expert forecasts. Prediction intervals come from the saved quantile and conformal models.</p></section></div>{module==='Models'&&<><h3>Expert forecast comparison</h3><table><thead><tr><th>Expert / model</th><th>Forecast ({value?.unit})</th><th>Weight</th></tr></thead><tbody>{value?.experts.map(e=><tr key={e.name}><td>{label(e.name)}</td><td>{fmt(e.value)}</td><td>{fmt(e.weight*100,1)}%</td></tr>)}<tr className="highlight"><td>HYDRA adaptive</td><td>{fmt(value?.value)}</td><td>100%</td></tr><tr><td>Seasonal LightGBM</td><td>{fmt(value?.lgbm)}</td><td>Comparison</td></tr></tbody></table><p className="note">AIFS, GFS, GEFS and nowcasting are integration pending. No learned weights for those sources exist in this checkpoint.</p></>}<div className="actions">{(['Models','Extreme Events','Impact & Risk','Verification','Provenance'] as Module[]).filter(x=>x!==module).map(m=><button key={m} onClick={()=>open(m)}>{m}<ArrowUpRight size={12}/></button>)}</div></>;
}
