"""WeatherGPT vocabulary: states/UTs, aliases, cities, variables, statistics, Hinglish terms."""
from __future__ import annotations

STATES = (
    "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh",
    "Chhattisgarh", "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana",
    "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Ladakh", "Lakshadweep",
    "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry",
    "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand",
    "West Bengal",
)

STATE_ALIASES = {
    "andaman": "Andaman and Nicobar Islands", "nicobar": "Andaman and Nicobar Islands", "andaman nicobar": "Andaman and Nicobar Islands",
    "a&n": "Andaman and Nicobar Islands", "andaman & nicobar": "Andaman and Nicobar Islands",
    "ap": "Andhra Pradesh", "andhra": "Andhra Pradesh", "arunachal": "Arunachal Pradesh",
    "assam": "Assam", "bihar": "Bihar", "chandigarh": "Chandigarh", "chattisgarh": "Chhattisgarh", "chhatisgarh": "Chhattisgarh",
    "cg": "Chhattisgarh", "dadra": "Dadra and Nagar Haveli and Daman and Diu", "daman": "Dadra and Nagar Haveli and Daman and Diu",
    "diu": "Dadra and Nagar Haveli and Daman and Diu", "dnh": "Dadra and Nagar Haveli and Daman and Diu",
    "nct": "Delhi", "new delhi": "Delhi", "dilli": "Delhi", "ncr": "Delhi", "goa": "Goa", "gujrat": "Gujarat", "gj": "Gujarat",
    "haryana": "Haryana", "hp": "Himachal Pradesh", "himachal": "Himachal Pradesh",
    "j&k": "Jammu and Kashmir", "jk": "Jammu and Kashmir", "j and k": "Jammu and Kashmir", "kashmir": "Jammu and Kashmir",
    "jammu": "Jammu and Kashmir", "jammu & kashmir": "Jammu and Kashmir", "jharkand": "Jharkhand",
    "ka": "Karnataka", "karnatak": "Karnataka", "keral": "Kerala", "keralam": "Kerala", "ladak": "Ladakh",
    "mp": "Madhya Pradesh", "madhyapradesh": "Madhya Pradesh", "mh": "Maharashtra", "maharastra": "Maharashtra",
    "maharashtr": "Maharashtra", "manipur": "Manipur", "meghalay": "Meghalaya", "mizoram": "Mizoram", "nagaland": "Nagaland",
    "orissa": "Odisha", "odisa": "Odisha", "pondicherry": "Puducherry", "pondy": "Puducherry", "puduchery": "Puducherry",
    "punjab": "Punjab", "rajastan": "Rajasthan", "rj": "Rajasthan", "sikkim": "Sikkim", "tn": "Tamil Nadu",
    "tamilnadu": "Tamil Nadu", "tamil nad": "Tamil Nadu", "telengana": "Telangana", "ts": "Telangana", "tripura": "Tripura",
    "up": "Uttar Pradesh", "uttarpradesh": "Uttar Pradesh", "uttaranchal": "Uttarakhand", "uk": "Uttarakhand",
    "uttrakhand": "Uttarakhand", "wb": "West Bengal", "bengal": "West Bengal", "westbengal": "West Bengal",
    "paschim banga": "West Bengal",
}
# short aliases that are also ordinary English words: only accepted in upper case or after "in"/"for"
AMBIGUOUS_ALIASES = {"ap", "up", "mp", "uk", "ka", "ts", "tn", "wb", "mh", "hp", "jk", "cg", "gj", "rj"}

INDIA_WORDS = ("india", "all india", "whole country", "country", "nationwide", "pan india", "bharat", "all states",
               "every state", "across india", "entire india", "national")
REGIONS = {
    "central india": "REGION : CENTRAL INDIA", "north west india": "REGION : NORTH WEST INDIA",
    "northwest india": "REGION : NORTH WEST INDIA", "south peninsula": "REGION : SOUTH PENINSULA",
    "south india": "REGION : SOUTH PENINSULA", "southern india": "REGION : SOUTH PENINSULA",
    "east and north east india": "REGION : EAST & NORTH EAST INDIA", "north east india": "REGION : EAST & NORTH EAST INDIA",
    "northeast india": "REGION : EAST & NORTH EAST INDIA", "northeast": "REGION : EAST & NORTH EAST INDIA",
}
REGION_STATES = {
    "REGION : SOUTH PENINSULA": ("Andhra Pradesh", "Karnataka", "Kerala", "Tamil Nadu", "Telangana", "Puducherry", "Lakshadweep", "Andaman and Nicobar Islands"),
    "REGION : CENTRAL INDIA": ("Madhya Pradesh", "Chhattisgarh", "Maharashtra", "Gujarat", "Goa", "Odisha", "Dadra and Nagar Haveli and Daman and Diu"),
    "REGION : NORTH WEST INDIA": ("Rajasthan", "Punjab", "Haryana", "Delhi", "Chandigarh", "Uttar Pradesh", "Uttarakhand", "Himachal Pradesh", "Jammu and Kashmir", "Ladakh"),
    "REGION : EAST & NORTH EAST INDIA": ("Bihar", "Jharkhand", "West Bengal", "Sikkim", "Assam", "Arunachal Pradesh", "Meghalaya", "Manipur", "Mizoram", "Nagaland", "Tripura"),
}

# city: (state, lat, lon)
CITIES = {
    "Port Blair": ("Andaman and Nicobar Islands", 11.62, 92.73),
    "Visakhapatnam": ("Andhra Pradesh", 17.69, 83.22), "Vizag": ("Andhra Pradesh", 17.69, 83.22),
    "Vijayawada": ("Andhra Pradesh", 16.51, 80.65), "Guntur": ("Andhra Pradesh", 16.31, 80.44),
    "Tirupati": ("Andhra Pradesh", 13.63, 79.42), "Nellore": ("Andhra Pradesh", 14.44, 79.99),
    "Kurnool": ("Andhra Pradesh", 15.83, 78.04), "Kakinada": ("Andhra Pradesh", 16.99, 82.25),
    "Amaravati": ("Andhra Pradesh", 16.51, 80.52), "Anantapur": ("Andhra Pradesh", 14.68, 77.60),
    "Itanagar": ("Arunachal Pradesh", 27.08, 93.61), "Tawang": ("Arunachal Pradesh", 27.59, 91.87),
    "Guwahati": ("Assam", 26.14, 91.74), "Dibrugarh": ("Assam", 27.47, 94.91), "Silchar": ("Assam", 24.83, 92.78),
    "Jorhat": ("Assam", 26.75, 94.20), "Tezpur": ("Assam", 26.63, 92.80),
    "Patna": ("Bihar", 25.59, 85.14), "Gaya": ("Bihar", 24.80, 85.00), "Bhagalpur": ("Bihar", 25.24, 86.98),
    "Muzaffarpur": ("Bihar", 26.12, 85.39), "Darbhanga": ("Bihar", 26.15, 85.90), "Purnia": ("Bihar", 25.78, 87.47),
    "Chandigarh": ("Chandigarh", 30.73, 76.78),
    "Raipur": ("Chhattisgarh", 21.25, 81.63), "Bilaspur": ("Chhattisgarh", 22.08, 82.15), "Bhilai": ("Chhattisgarh", 21.21, 81.38),
    "Jagdalpur": ("Chhattisgarh", 19.08, 82.02), "Korba": ("Chhattisgarh", 22.36, 82.75),
    "Silvassa": ("Dadra and Nagar Haveli and Daman and Diu", 20.27, 73.02), "Daman": ("Dadra and Nagar Haveli and Daman and Diu", 20.40, 72.83),
    "New Delhi": ("Delhi", 28.61, 77.21), "Delhi": ("Delhi", 28.61, 77.21),
    "Panaji": ("Goa", 15.49, 73.83), "Margao": ("Goa", 15.27, 73.96), "Vasco da Gama": ("Goa", 15.40, 73.81),
    "Ahmedabad": ("Gujarat", 23.02, 72.57), "Surat": ("Gujarat", 21.17, 72.83), "Vadodara": ("Gujarat", 22.31, 73.18),
    "Baroda": ("Gujarat", 22.31, 73.18), "Rajkot": ("Gujarat", 22.30, 70.80), "Bhavnagar": ("Gujarat", 21.76, 72.15),
    "Jamnagar": ("Gujarat", 22.47, 70.06), "Gandhinagar": ("Gujarat", 23.22, 72.65), "Bhuj": ("Gujarat", 23.24, 69.67),
    "Junagadh": ("Gujarat", 21.52, 70.46), "Dwarka": ("Gujarat", 22.24, 68.97),
    "Gurugram": ("Haryana", 28.46, 77.03), "Gurgaon": ("Haryana", 28.46, 77.03), "Faridabad": ("Haryana", 28.41, 77.32),
    "Panipat": ("Haryana", 29.39, 76.97), "Ambala": ("Haryana", 30.38, 76.78), "Hisar": ("Haryana", 29.15, 75.72),
    "Rohtak": ("Haryana", 28.90, 76.61), "Karnal": ("Haryana", 29.69, 76.99),
    "Shimla": ("Himachal Pradesh", 31.10, 77.17), "Manali": ("Himachal Pradesh", 32.24, 77.19),
    "Dharamshala": ("Himachal Pradesh", 32.22, 76.32), "Mandi": ("Himachal Pradesh", 31.71, 76.93), "Kullu": ("Himachal Pradesh", 31.96, 77.11),
    "Srinagar": ("Jammu and Kashmir", 34.08, 74.80), "Jammu City": ("Jammu and Kashmir", 32.73, 74.86),
    "Gulmarg": ("Jammu and Kashmir", 34.05, 74.38), "Pahalgam": ("Jammu and Kashmir", 34.02, 75.32), "Anantnag": ("Jammu and Kashmir", 33.73, 75.15),
    "Ranchi": ("Jharkhand", 23.34, 85.31), "Jamshedpur": ("Jharkhand", 22.80, 86.20), "Dhanbad": ("Jharkhand", 23.80, 86.43),
    "Bokaro": ("Jharkhand", 23.67, 86.15), "Deoghar": ("Jharkhand", 24.48, 86.70),
    "Bengaluru": ("Karnataka", 12.97, 77.59), "Bangalore": ("Karnataka", 12.97, 77.59), "Mysuru": ("Karnataka", 12.30, 76.64),
    "Mysore": ("Karnataka", 12.30, 76.64), "Mangaluru": ("Karnataka", 12.91, 74.86), "Mangalore": ("Karnataka", 12.91, 74.86),
    "Hubballi": ("Karnataka", 15.36, 75.12), "Hubli": ("Karnataka", 15.36, 75.12), "Belagavi": ("Karnataka", 15.85, 74.50),
    "Belgaum": ("Karnataka", 15.85, 74.50), "Kalaburagi": ("Karnataka", 17.33, 76.83), "Gulbarga": ("Karnataka", 17.33, 76.83),
    "Udupi": ("Karnataka", 13.34, 74.75), "Shivamogga": ("Karnataka", 13.93, 75.57), "Ballari": ("Karnataka", 15.14, 76.92),
    "Davanagere": ("Karnataka", 14.46, 75.92), "Madikeri": ("Karnataka", 12.42, 75.74), "Coorg": ("Karnataka", 12.42, 75.74),
    "Chikmagalur": ("Karnataka", 13.32, 75.77), "Hassan": ("Karnataka", 13.00, 76.10), "Tumakuru": ("Karnataka", 13.34, 77.10),
    "Thiruvananthapuram": ("Kerala", 8.52, 76.94), "Trivandrum": ("Kerala", 8.52, 76.94), "Kochi": ("Kerala", 9.93, 76.27),
    "Cochin": ("Kerala", 9.93, 76.27), "Ernakulam": ("Kerala", 9.98, 76.30), "Kozhikode": ("Kerala", 11.26, 75.78),
    "Calicut": ("Kerala", 11.26, 75.78), "Thrissur": ("Kerala", 10.53, 76.21), "Kannur": ("Kerala", 11.87, 75.37),
    "Kollam": ("Kerala", 8.89, 76.61), "Alappuzha": ("Kerala", 9.49, 76.34), "Alleppey": ("Kerala", 9.49, 76.34),
    "Palakkad": ("Kerala", 10.79, 76.65), "Kottayam": ("Kerala", 9.59, 76.52), "Munnar": ("Kerala", 10.09, 77.06),
    "Wayanad": ("Kerala", 11.69, 76.08), "Idukki": ("Kerala", 9.85, 76.97), "Malappuram": ("Kerala", 11.07, 76.07),
    "Pathanamthitta": ("Kerala", 9.26, 76.79), "Kasaragod": ("Kerala", 12.50, 75.00),
    "Leh": ("Ladakh", 34.15, 77.58), "Kargil": ("Ladakh", 34.56, 76.13),
    "Kavaratti": ("Lakshadweep", 10.57, 72.64),
    "Bhopal": ("Madhya Pradesh", 23.26, 77.41), "Indore": ("Madhya Pradesh", 22.72, 75.86), "Jabalpur": ("Madhya Pradesh", 23.18, 79.99),
    "Gwalior": ("Madhya Pradesh", 26.22, 78.18), "Ujjain": ("Madhya Pradesh", 23.18, 75.78), "Sagar": ("Madhya Pradesh", 23.84, 78.74),
    "Rewa": ("Madhya Pradesh", 24.53, 81.30), "Satna": ("Madhya Pradesh", 24.60, 80.83), "Khajuraho": ("Madhya Pradesh", 24.85, 79.93),
    "Mumbai": ("Maharashtra", 19.08, 72.88), "Bombay": ("Maharashtra", 19.08, 72.88), "Pune": ("Maharashtra", 18.52, 73.86),
    "Nagpur": ("Maharashtra", 21.15, 79.09), "Nashik": ("Maharashtra", 20.00, 73.79), "Aurangabad": ("Maharashtra", 19.88, 75.34),
    "Chhatrapati Sambhajinagar": ("Maharashtra", 19.88, 75.34), "Thane": ("Maharashtra", 19.22, 72.98),
    "Navi Mumbai": ("Maharashtra", 19.03, 73.03), "Solapur": ("Maharashtra", 17.66, 75.91), "Kolhapur": ("Maharashtra", 16.70, 74.24),
    "Amravati": ("Maharashtra", 20.93, 77.75), "Nanded": ("Maharashtra", 19.15, 77.31), "Ratnagiri": ("Maharashtra", 16.99, 73.30),
    "Satara": ("Maharashtra", 17.68, 74.02), "Latur": ("Maharashtra", 18.40, 76.56), "Akola": ("Maharashtra", 20.70, 77.00),
    "Mahabaleshwar": ("Maharashtra", 17.92, 73.66), "Lonavala": ("Maharashtra", 18.75, 73.41), "Jalgaon": ("Maharashtra", 21.01, 75.56),
    "Imphal": ("Manipur", 24.82, 93.94), "Shillong": ("Meghalaya", 25.58, 91.89), "Cherrapunji": ("Meghalaya", 25.27, 91.73),
    "Sohra": ("Meghalaya", 25.27, 91.73), "Mawsynram": ("Meghalaya", 25.30, 91.58), "Tura": ("Meghalaya", 25.51, 90.22),
    "Aizawl": ("Mizoram", 23.73, 92.72), "Kohima": ("Nagaland", 25.67, 94.11), "Dimapur": ("Nagaland", 25.91, 93.73),
    "Bhubaneswar": ("Odisha", 20.30, 85.82), "Cuttack": ("Odisha", 20.46, 85.88), "Puri": ("Odisha", 19.81, 85.83),
    "Rourkela": ("Odisha", 22.26, 84.85), "Berhampur": ("Odisha", 19.31, 84.79), "Sambalpur": ("Odisha", 21.47, 83.97),
    "Balasore": ("Odisha", 21.49, 86.93), "Paradip": ("Odisha", 20.32, 86.61),
    "Puducherry City": ("Puducherry", 11.94, 79.81), "Karaikal": ("Puducherry", 10.93, 79.84),
    "Ludhiana": ("Punjab", 30.90, 75.86), "Amritsar": ("Punjab", 31.63, 74.87), "Jalandhar": ("Punjab", 31.33, 75.58),
    "Patiala": ("Punjab", 30.34, 76.39), "Bathinda": ("Punjab", 30.21, 74.95), "Mohali": ("Punjab", 30.70, 76.72),
    "Jaipur": ("Rajasthan", 26.91, 75.79), "Jodhpur": ("Rajasthan", 26.24, 73.02), "Udaipur": ("Rajasthan", 24.59, 73.71),
    "Kota": ("Rajasthan", 25.18, 75.83), "Bikaner": ("Rajasthan", 28.02, 73.31), "Ajmer": ("Rajasthan", 26.45, 74.64),
    "Jaisalmer": ("Rajasthan", 26.92, 70.91), "Barmer": ("Rajasthan", 25.75, 71.39), "Churu": ("Rajasthan", 28.30, 74.95),
    "Phalodi": ("Rajasthan", 27.13, 72.36), "Mount Abu": ("Rajasthan", 24.59, 72.71), "Alwar": ("Rajasthan", 27.55, 76.60),
    "Gangtok": ("Sikkim", 27.33, 88.61),
    "Chennai": ("Tamil Nadu", 13.08, 80.27), "Madras": ("Tamil Nadu", 13.08, 80.27), "Coimbatore": ("Tamil Nadu", 11.02, 76.96),
    "Madurai": ("Tamil Nadu", 9.93, 78.12), "Tiruchirappalli": ("Tamil Nadu", 10.79, 78.70), "Trichy": ("Tamil Nadu", 10.79, 78.70),
    "Salem": ("Tamil Nadu", 11.66, 78.15), "Tirunelveli": ("Tamil Nadu", 8.71, 77.76), "Vellore": ("Tamil Nadu", 12.92, 79.13),
    "Thoothukudi": ("Tamil Nadu", 8.76, 78.13), "Tuticorin": ("Tamil Nadu", 8.76, 78.13), "Ooty": ("Tamil Nadu", 11.41, 76.70),
    "Kodaikanal": ("Tamil Nadu", 10.24, 77.49), "Kanyakumari": ("Tamil Nadu", 8.09, 77.54), "Thanjavur": ("Tamil Nadu", 10.79, 79.14),
    "Erode": ("Tamil Nadu", 11.34, 77.72), "Tiruppur": ("Tamil Nadu", 11.11, 77.34), "Rameswaram": ("Tamil Nadu", 9.29, 79.31),
    "Cuddalore": ("Tamil Nadu", 11.75, 79.75), "Nagapattinam": ("Tamil Nadu", 10.77, 79.84),
    "Hyderabad": ("Telangana", 17.39, 78.49), "Secunderabad": ("Telangana", 17.44, 78.50), "Warangal": ("Telangana", 17.97, 79.59),
    "Nizamabad": ("Telangana", 18.67, 78.09), "Karimnagar": ("Telangana", 18.44, 79.13), "Khammam": ("Telangana", 17.25, 80.15),
    "Agartala": ("Tripura", 23.83, 91.29),
    "Lucknow": ("Uttar Pradesh", 26.85, 80.95), "Kanpur": ("Uttar Pradesh", 26.45, 80.33), "Varanasi": ("Uttar Pradesh", 25.32, 82.97),
    "Banaras": ("Uttar Pradesh", 25.32, 82.97), "Agra": ("Uttar Pradesh", 27.18, 78.01), "Prayagraj": ("Uttar Pradesh", 25.44, 81.85),
    "Allahabad": ("Uttar Pradesh", 25.44, 81.85), "Noida": ("Uttar Pradesh", 28.54, 77.39), "Ghaziabad": ("Uttar Pradesh", 28.67, 77.45),
    "Meerut": ("Uttar Pradesh", 28.98, 77.71), "Gorakhpur": ("Uttar Pradesh", 26.76, 83.37), "Bareilly": ("Uttar Pradesh", 28.37, 79.43),
    "Aligarh": ("Uttar Pradesh", 27.88, 78.08), "Mathura": ("Uttar Pradesh", 27.49, 77.67), "Ayodhya": ("Uttar Pradesh", 26.80, 82.20),
    "Jhansi": ("Uttar Pradesh", 25.45, 78.57), "Moradabad": ("Uttar Pradesh", 28.84, 78.77),
    "Dehradun": ("Uttarakhand", 30.32, 78.03), "Haridwar": ("Uttarakhand", 29.95, 78.16), "Rishikesh": ("Uttarakhand", 30.09, 78.27),
    "Nainital": ("Uttarakhand", 29.39, 79.45), "Mussoorie": ("Uttarakhand", 30.46, 78.07), "Haldwani": ("Uttarakhand", 29.22, 79.51),
    "Kedarnath": ("Uttarakhand", 30.73, 79.07), "Badrinath": ("Uttarakhand", 30.74, 79.49),
    "Kolkata": ("West Bengal", 22.57, 88.36), "Calcutta": ("West Bengal", 22.57, 88.36), "Howrah": ("West Bengal", 22.59, 88.31),
    "Darjeeling": ("West Bengal", 27.04, 88.26), "Siliguri": ("West Bengal", 26.73, 88.40), "Durgapur": ("West Bengal", 23.52, 87.31),
    "Asansol": ("West Bengal", 23.68, 86.98), "Kharagpur": ("West Bengal", 22.35, 87.23), "Digha": ("West Bengal", 21.63, 87.51),
}

VARIABLES = {
    "rainfall": ("rain", "rainfall", "rains", "raining", "rainy", "precipitation", "precip", "shower", "showers", "downpour",
                 "drizzle", "wet", "wettest", "driest", "dry", "barish", "baarish", "barsaat", "varsha", "baarish", "monsoon rain",
                 "rainfall amount", "mm of rain", "how much it rained", "pour", "storm rain", "cloudburst"),
    "temperature": ("temperature", "temp", "temps", "hot", "hottest", "cold", "coldest", "warm", "warmest", "cool", "coolest",
                    "heat", "garmi", "thand", "thandi", "degrees", "celsius", "°c", "tapman", "mercury", "chilly", "freezing"),
    "humidity": ("humidity", "humid", "relative humidity", "rh", "muggy", "sticky", "moisture in air", "nami", "umas"),
    "wind": ("wind", "winds", "windy", "wind speed", "breeze", "breezy", "hawa", "toofan"),
    "wind_gust": ("gust", "gusts", "wind gust", "gusty", "squall"),
    "pressure": ("pressure", "msl", "mslp", "sea level pressure", "barometric", "hpa", "air pressure"),
    "cloud": ("cloud", "clouds", "cloudy", "cloud cover", "overcast", "badal", "sunny", "clear sky"),
    "cape": ("cape", "convective", "instability", "thunderstorm potential", "convective energy"),
    "thunderstorm": ("thunderstorm", "thunderstorms", "lightning", "thunder", "storm", "storms", "bijli", "toofan"),
    "solar": ("solar radiation", "sunshine", "radiation", "solar", "ssrd", "irradiance"),
    "dew_point": ("dew point", "dewpoint", "dew"),
    "water_vapour": ("water vapour", "water vapor", "tcwv", "precipitable water", "moisture"),
    "soil_moisture": ("soil moisture", "soil wetness", "ground moisture"),
    "heat_stress": ("heat stress", "wet bulb", "wet-bulb", "feels like", "heat index"),
}
LIVE_LAYER_FOR = {
    "temperature": "live_weather", "rainfall": "open_meteo_rainfall", "wind": "open_meteo_wind_speed",
    "humidity": "open_meteo_humidity", "wind_gust": "open_meteo_wind_gust", "thunderstorm": "open_meteo_lightning",
    "cape": "open_meteo_thunderstorm", "heat_stress": "open_meteo_heat_stress", "soil_moisture": "open_meteo_soil_moisture",
}

STATISTICS = {
    "total": ("total", "sum", "cumulative", "accumulated", "overall", "how much rain fell", "altogether", "kitni barish"),
    "mean": ("average", "avg", "mean", "typical", "on average", "normally"),
    "max": ("maximum", "max", "highest", "peak", "most", "heaviest", "wettest", "hottest", "warmest", "windiest", "strongest", "top"),
    "min": ("minimum", "min", "lowest", "least", "driest", "coldest", "coolest", "calmest", "weakest", "bottom"),
    "count": ("how many days", "number of days", "count", "days with", "days when", "how often", "frequency"),
    "trend": ("trend", "increasing", "decreasing", "rising", "falling", "getting wetter", "getting drier", "pattern over",
              "over time", "trajectory", "progression"),
}

SOURCE_HINTS = {
    "imd": ("imd", "india meteorological", "observed", "observation", "official", "actual rainfall", "recorded", "station"),
    "era5": ("era5", "reanalysis", "era 5"),
    "hydra": ("hydra", "model", "blend", "neural gate", "gate", "expert", "prediction", "predicted", "replay", "backtest"),
    "ecmwf": ("ecmwf", "ifs", "analysis snapshot", "european model"),
    "live": ("live", "now", "right now", "currently", "current", "at the moment", "abhi", "real time", "realtime", "today"),
    "meteostat": ("meteostat",),
}

HINGLISH = {
    "kal": "tomorrow", "aaj": "today", "abhi": "now", "parso": "day after tomorrow", "kitni": "how much", "kitna": "how much",
    "kya": "what", "kaisa": "how", "kaisi": "how", "mausam": "weather", "mosam": "weather", "barish": "rain", "baarish": "rain",
    "garmi": "heat", "thand": "cold", "hawa": "wind", "mein": "in", "hogi": "will be", "hoga": "will be", "hua": "was",
    "hui": "was", "pichle": "last", "pichhle": "last", "hafte": "week", "mahine": "month", "sabse": "most", "zyada": "more",
    "jyada": "more", "kam": "less", "kaha": "where", "kahan": "where", "kab": "when", "kyun": "why", "kyu": "why",
    "batao": "tell", "bata": "tell", "dikhao": "show", "aur": "and", "ya": "or", "kaun": "which", "konsa": "which",
    "kaunsa": "which", "rajya": "state", "din": "day", "raat": "night", "chhata": "umbrella", "chahiye": "needed",
}

ADVICE_TOPICS = {
    "umbrella": ("umbrella", "raincoat", "chhata", "carry", "get wet"),
    "travel": ("travel", "trip", "visit", "tour", "drive", "road trip", "flight", "journey", "trek", "vacation", "holiday"),
    "agriculture": ("farm", "farmer", "farming", "crop", "sow", "sowing", "harvest", "irrigation", "irrigate", "kharif", "rabi",
                    "paddy", "kheti", "kisan", "fertiliser", "fertilizer", "spray", "pesticide"),
    "outdoor": ("outdoor", "outside", "cricket", "match", "picnic", "jog", "run", "walk", "wedding", "event", "construction",
                "concert", "game"),
    "flood": ("flood", "flooding", "waterlogging", "inundation", "landslide", "baadh"),
    "health": ("heatstroke", "heat stroke", "dehydration", "asthma", "health", "elderly", "kids safe"),
    "energy": ("solar panel", "solar power", "energy", "power demand", "wind farm", "electricity"),
    "marine": ("fishing", "fishermen", "sea", "boat", "port", "shipping", "ship"),
    "aviation": ("aviation", "airport", "runway", "fly"),
}
